# Generated by Django 5.2.1 on 2025-06-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('mountains', 'Mountains'), ('temples', 'Temples'), ('rivers', 'Rivers'), ('treks', 'Treks'), ('sunrise', 'Sunrise Views')], max_length=50)),
                ('image', models.ImageField(upload_to='travel_places/')),
                ('video', models.FileField(blank=True, null=True, upload_to='travel_places/videos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='firebase_uid',
            field=models.CharField(blank=True, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(default='default_user', max_length=150, unique=True),
        ),
    ]
