# Generated by Django 5.2.1 on 2025-06-22 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='travelplace',
            name='image',
        ),
        migrations.RemoveField(
            model_name='travelplace',
            name='video',
        ),
        migrations.AddField(
            model_name='travelplace',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_places/covers/'),
        ),
        migrations.CreateModel(
            name='TravelPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='travel_places/images/')),
                ('travel_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.travelplace')),
            ],
        ),
        migrations.CreateModel(
            name='TravelPlaceVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='travel_places/videos/')),
                ('travel_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='api.travelplace')),
            ],
        ),
    ]
