# Generated by Django 5.2.1 on 2025-06-22 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_travelplace_image_remove_travelplace_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='travel_places/videos/'),
        ),
        migrations.AlterField(
            model_name='travelplaceimage',
            name='image',
            field=models.ImageField(upload_to='travel_places/gallery/'),
        ),
        migrations.DeleteModel(
            name='TravelPlaceVideo',
        ),
    ]
