# Generated by Django 5.2.1 on 2025-06-23 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_travelplace_video_alter_travelplaceimage_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='available_transport',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplace',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelplace',
            name='duration_to_visit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelplace',
            name='estimated_cost',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='travelplace',
            name='full_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplace',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='travelplace',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='travelplace',
            name='cover_image',
            field=models.ImageField(null=True, upload_to='travel_places/covers/'),
        ),
    ]
