# Generated by Django 5.2.1 on 2025-06-23 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_travelplace_available_transport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='travelplace',
            name='best_time_to_visit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='travelplace',
            name='category',
            field=models.CharField(choices=[('mountains', 'Mountains'), ('temples', 'Temples'), ('rivers', 'Rivers'), ('city', 'City'), ('valley', 'Valley'), ('treks', 'Treks'), ('lakes', 'Lakes')], max_length=50),
        ),
        migrations.AlterField(
            model_name='travelplace',
            name='duration_to_visit',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='travelplace',
            name='estimated_cost',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
