# Generated by Django 5.2.1 on 2025-06-26 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_travelplace_is_popular_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSubmittedPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('mountains', 'Mountains'), ('temples', 'Temples'), ('rivers', 'Rivers'), ('city', 'City'), ('valley', 'Valley'), ('treks', 'Treks'), ('lakes', 'Lakes')], max_length=50)),
                ('cover_image', models.ImageField(null=True, upload_to='user_places/covers/')),
                ('video', models.FileField(blank=True, null=True, upload_to='user_places/videos/')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('estimated_cost', models.CharField(blank=True, max_length=200, null=True)),
                ('best_time_to_visit', models.CharField(blank=True, max_length=200, null=True)),
                ('available_transport', models.TextField(blank=True, null=True)),
                ('duration_to_visit', models.CharField(blank=True, max_length=200, null=True)),
                ('full_address', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('is_approved', models.BooleanField(default=False)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserSubmittedPlaceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_places/gallery/')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.usersubmittedplace')),
            ],
        ),
    ]
