# Generated by Django 5.2.1 on 2025-07-01 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_post_userprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='profile_photos/'),
        ),
    ]
