# Generated by Django 5.2.1 on 2025-07-03 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='travelplaceimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='travel_places/gallery/'),
        ),
    ]
