# Generated by Django 5.2.1 on 2025-07-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_notification_is_active_alter_notification_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('follow', 'Follow'), ('follow_back', 'Followed Back')], max_length=50),
        ),
    ]
