// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC3c1wLuwhg1s7XTT8Ta1fv1rp2xe-ofjk',
    appId: '1:92205541700:web:348604e8de61ae69774f11',
    messagingSenderId: '92205541700',
    projectId: 'travelapp-166fa',
    authDomain: 'travelapp-166fa.firebaseapp.com',
    storageBucket: 'travelapp-166fa.firebasestorage.app',
    measurementId: 'G-93P3BZSQJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyApeyfBx6wvmF9ENH95b1qcoYOVf1aODjg',
    appId: '1:92205541700:android:8b56e58670fbca47774f11',
    messagingSenderId: '92205541700',
    projectId: 'travelapp-166fa',
    storageBucket: 'travelapp-166fa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAND1gBV8ngmlamFvSI0Zj6JAh1tdcekUM',
    appId: '1:92205541700:ios:e3f2b18f9bfd5914774f11',
    messagingSenderId: '92205541700',
    projectId: 'travelapp-166fa',
    storageBucket: 'travelapp-166fa.firebasestorage.app',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAND1gBV8ngmlamFvSI0Zj6JAh1tdcekUM',
    appId: '1:92205541700:ios:e3f2b18f9bfd5914774f11',
    messagingSenderId: '92205541700',
    projectId: 'travelapp-166fa',
    storageBucket: 'travelapp-166fa.firebasestorage.app',
    iosBundleId: 'com.example.travelapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC3c1wLuwhg1s7XTT8Ta1fv1rp2xe-ofjk',
    appId: '1:92205541700:web:0dd6bafb42fad1bc774f11',
    messagingSenderId: '92205541700',
    projectId: 'travelapp-166fa',
    authDomain: 'travelapp-166fa.firebaseapp.com',
    storageBucket: 'travelapp-166fa.firebasestorage.app',
    measurementId: 'G-CRKLZDLPVD',
  );
}
